### ISSUE TITLE
Slackに投稿する

### ISSUE THREAD

**Issue by hirossan4049** [hirossan4049/LogReport#2]
## 期待動作
```bash
$ python3 post_slack.py username date メッセージ
OK
```

slack投稿例
```
2023年2月23日: hirossan4049: 頑張った
```

- usernameはgithubのユーザー名
- dateは作業日
- メッセージはスペースが入る可能性もある
- とりあえず、特定のチャンネルで送信

**Comment by alok0814** [comment]
とりあえず、自分のアカウントで投稿する形で実装してます
ボットだと人数が多い場合めんどくさくなりますかね？

**Comment by hirossan4049** [comment]
とりあえずは問題ないと思います！
